_BASE_: "../Base-RCNN-C4.yaml"
MODEL:
#  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
#  WEIGHTS: "/tmp/pycharm_project_652/output/faster_incr/model_0014999.pth"
#  WEIGHTS: "/home/joseph/detectron2/output/15_class/model_final.pth"
  WEIGHTS: "/home/joseph/detectron2/output/temperature_3/model_final.pth"
  MASK_ON: False
  RESNETS:
    DEPTH: 50
  ROI_HEADS:
    # Maximum number of foreground classes to expect
    NUM_CLASSES: 20
    # Flag to turn on/off Incremental Learning
    LEARN_INCREMENTALLY: False
    # Flag to select whether to learn base classes or new expanded classes
    TRAIN_ON_BASE_CLASSES: False
    # Number of base classes; these classes would be trained if TRAIN_ON_BASE_CLASSES is set to True
    NUM_BASE_CLASSES: 15
    # Number of novel classes; these classes would be trained if TRAIN_ON_BASE_CLASSES is set to False
    NUM_NOVEL_CLASSES: 5
  RPN:
    FREEZE_WEIGHTS: False
INPUT:
  MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800)
  MIN_SIZE_TEST: 800
DATASETS:
  TRAIN: ('voc_2007_trainval',)
  TEST: ('voc_2007_test',)
SOLVER:
  STEPS: (3000, 4000) # 21000, 22000
  MAX_ITER: 22500  # 17.4 epochs -> 18000 iterations 4500,
  WARMUP_ITERS: 20 # 100
OUTPUT_DIR: ./output/temperature_3
VIS_PERIOD: 4000
DISTILL:
  ENABLE: True
  BACKBONE: True
  RPN: False
  ROI_HEADS: True